branches:
  only:
  - main
  - dev
  - /^issue-\d+$/
language: android
dist: trusty
jdk: openjdk11
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
   - touch $HOME/.android/repositories.cfg
   # Android API Level 32
   - yes | sdkmanager "platforms;android-32"
   - yes | sdkmanager "build-tools;32.0.0"
