branches:
  only:
  - main
  - dev
  - /^issue-\d+$/
language: android
dist: trusty
jdk: openjdk11
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
